version: '3'

services:
  react-app:
    build:
      context: ./  
      dockerfile: Dockerfile.react
    ports:
      - "5135:5135"
    volumes:
      - ./usr/src/app  

  django-server:
    build:
      context: ./  
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    depends_on:
      - react-app
    volumes:
      - ./server:/usr/src/app  
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.sqlite3
      - DJANGO_DB_NAME=mydatabase
